# Generated by Django 5.2.3 on 2025-07-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id_abonnement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('critere', models.CharField(max_length=200)),
                ('plage', models.CharField(max_length=100)),
                ('validite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'abonnement',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_administrateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id_professionnel', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'professionnel',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='SouscriptionProf',
            fields=[
                ('id_souscription_prof', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('abonnement', models.ForeignKey(db_column='id_abonnement', on_delete=django.db.models.deletion.CASCADE, to='profils.abonnement')),
                ('professionnel', models.ForeignKey(db_column='id_professionnel', on_delete=django.db.models.deletion.CASCADE, to='profils.professionnel')),
            ],
            options={
                'db_table': 'souscription_prof',
            },
        ),
        migrations.AddField(
            model_name='abonnement',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='profils.type'),
        ),
    ]
