# Generated by Django 5.2.3 on 2025-07-18 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id_abonnement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('critere', models.CharField(max_length=200)),
                ('plage', models.CharField(max_length=100)),
                ('validite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'abonnement',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('admin', 'Administrateur'), ('prof', 'Professionnel'), ('ent', 'Entreprise')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('secteur', models.CharField(max_length=100)),
                ('besoin', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professionnel',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id_competence', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='profils.professionnel')),
            ],
            options={
                'db_table': 'competence',
            },
        ),
        migrations.CreateModel(
            name='SouscriptionProf',
            fields=[
                ('id_souscription_prof', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('abonnement', models.ForeignKey(db_column='id_abonnement', on_delete=django.db.models.deletion.CASCADE, to='profils.abonnement')),
                ('professionnel', models.ForeignKey(db_column='id_professionnel', on_delete=django.db.models.deletion.CASCADE, to='profils.professionnel')),
            ],
            options={
                'db_table': 'souscription_prof',
            },
        ),
        migrations.AddField(
            model_name='abonnement',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='profils.type'),
        ),
    ]
